# Generated by Django 5.0 on 2025-01-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrecpies', '0006_remove_userprofile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='default_serving',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
