# Generated by Django 5.0 on 2025-01-02 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrecpies', '0007_recipe_default_serving'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_ingridents',
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=50)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='myrecpies.recipe')),
            ],
        ),
    ]
